version: "3.8"

services:
  kit_nginx:
    container_name: kit_nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3200:3200"
      - "3201:3201"
      - "3300:3300"
      - "3301:3301"
    depends_on:
      - kit_php_fpm
    restart: unless-stopped

  kit_php_fpm:
    platform: linux/x86_64
    container_name: kit_php_fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - kit_postgres

  kit_php_cli:
    platform: linux/x86_64
    container_name: kit_php_cli
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - kit_postgres

  kit_postgres:
    container_name: kit_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - kit-postgres-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  kit_redis:
    container_name: kit_redis
    image: redis:6-alpine
    volumes:
      - kit_redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  default:
    external: true
    name: kit_network

volumes:
  kit-postgres-db-data:
  kit_redis_data:
